version: "3"
services:
  go:
    build:
      context: ../
      dockerfile: .devcontainer/infra/go/Dockerfile
      args:
        - APP_ROOT=$APP_ROOT
    env_file:
      - .env
    tty: true
    ports:
      - ${GO_PORT}:${GO_PORT}
    volumes:
      - ../:$APP_ROOT
      - ~/.gitconfig:/root/.gitconfig
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:

volumes:
  go-modules:
