name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Download dependencies
        run: |
          go mod download
          cd infra
          go mod download

      - name: Run go vet
        run: |
          go vet ./cmd/... ./internal/...
          cd infra
          go vet .

      - name: Run tests
        run: |
          go test ./cmd/... ./internal/...
          cd infra
          go test .
